services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"