CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(38, 2) NOT NULL
);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    product_id BIGINT NOT NULL REFERENCES product(id),
    quantity INTEGER NOT NULL,
    price_at_purchase NUMERIC(38, 2) NOT NULL
);

INSERT INTO product (name, price, stock_quantity) VALUES ('Mechanical Keyboard', 120.00, 50);
INSERT INTO product (name, price, stock_quantity) VALUES ('Wireless Mouse', 45.00, 100);
INSERT INTO product (name, price, stock_quantity) VALUES ('27-inch Monitor', 350.00, 15);