spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:inventory_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secretpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true